version: "3.8"

services:
  db:
    image: postgres:15
    container_name: actix_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: actixdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: actix_backend
    restart: always
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/actixdb
      JWT_SECRET: supersecretkey
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
